# Copyright (c) 2022, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c nvidia -c rapidsai
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ.get('RAPIDS_CUDA_VERSION', '11.5.2').split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set cuda_spec = ">=" + cuda_major ~ ",<" + (cuda_major | int + 1) ~ ".0a0" %} # i.e. >=11,<12.0a0

package:
  name: libraft-split

source:
  git_url: ../../..

outputs:
  - name: libraft-headers
    version: {{ version }}
    script: build_libraft_headers.sh
    build:
      script_env: &script_env
        - PARALLEL_LEVEL
        - CMAKE_GENERATOR
        - CMAKE_C_COMPILER_LAUNCHER
        - CMAKE_CXX_COMPILER_LAUNCHER
        - CMAKE_CUDA_COMPILER_LAUNCHER
        - SCCACHE_S3_KEY_PREFIX=libraft-aarch64 # [aarch64]
        - SCCACHE_S3_KEY_PREFIX=libraft-linux64 # [linux64]
        - SCCACHE_BUCKET
        - SCCACHE_REGION
        - SCCACHE_IDLE_TIMEOUT
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }} {{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - sysroot_{{ target_platform }} {{ sysroot_version }}
      host:
        - cudatoolkit {{ cuda_version }}.*
        - cuda-profiler-api {{ cuda_profiler_api_version }}
        - libcublas-dev {{ libcublas_version }}
        - libcurand-dev {{ libcurand_version }}
        - libcusolver-dev {{ libcusolver_version }}
        - libcusparse-dev {{ libcusparse_version }}
        - librmm {{ minor_version }}.*
      run:
        - cudatoolkit {{ cuda_spec }}
        - cuda-profiler-api {{ cuda_profiler_api_version }}
        - libcublas-dev {{ libcublas_version }}
        - libcurand-dev {{ libcurand_version }}
        - libcusolver-dev {{ libcusolver_version }}
        - libcusparse-dev {{ libcusparse_version }}
        - librmm {{ minor_version }}.*
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libraft-headers library
  - name: libraft-distance
    version: {{ version }}
    script: build_libraft_distance.sh
    build:
      script_env: *script_env
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }} {{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - sysroot_{{ target_platform }} {{ sysroot_version }}
      host:
        - {{ pin_subpackage('libraft-headers', exact=True) }}
      run:
        - {{ pin_subpackage('libraft-headers', exact=True) }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libraft-distance library
  - name: libraft-nn
    version: {{ version }}
    script: build_libraft_nn.sh
    build:
      script_env: *script_env
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }} {{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - sysroot_{{ target_platform }} {{ sysroot_version }}
      host:
        - faiss-proc=*=cuda
        - lapack
        - libfaiss {{ libfaiss_version }}
        - {{ pin_subpackage('libraft-headers', exact=True) }}
      run:
        - faiss-proc=*=cuda
        - libfaiss {{ libfaiss_version }}
        - {{ pin_subpackage('libraft-headers', exact=True) }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libraft-nn library
  - name: libraft-tests
    version: {{ version }}
    script: build_libraft_tests.sh
    build:
      script_env: *script_env
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }} {{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - sysroot_{{ target_platform }} {{ sysroot_version }}
      host:
        - gmock {{ gtest_version }}
        - gtest {{ gtest_version }}
        - {{ pin_subpackage('libraft-distance', exact=True) }}
        - {{ pin_subpackage('libraft-headers', exact=True) }}
        - {{ pin_subpackage('libraft-nn', exact=True) }}
      run:
        - gmock {{ gtest_version }}
        - gtest {{ gtest_version }}
        - {{ pin_subpackage('libraft-distance', exact=True) }}
        - {{ pin_subpackage('libraft-headers', exact=True) }}
        - {{ pin_subpackage('libraft-nn', exact=True) }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libraft tests
